### ISSUE TITLE
browser closes automatically after reaching to instagram page

### ISSUE THREAD

**Issue by chiroxez** [dv1pr/Web-Scraping-Tutorial#4]
DevTools listening on ws://127.0.0.1:12281/devtools/browser/f1e41c10-05c6-4d0b-9535-d8082f0feb53
Logging in...
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: call function result missing 'value' (Selenium::WebDriver::Error::UnknownError)
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.17134 x86_64)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/oss/bridge.rb:387:in `clear_element'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/common/element.rb:169:in `clear'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.14.0/lib/watir/user_editable.rb:11:in `block in set'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.14.0/lib/watir/elements/element.rb:758:in `element_call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/watir-6.14.0/lib/watir/user_editable.rb:10:in `set'
        from C:/Users/Chiro/Desktop/files/Web-Scraping-Tutorial-master/auto_liker.rb:19:in `<main>'

**Comment by pr0ject404** [comment]
You're using Windows 10, Make sure you have all the libraries installed or Install Ruby 2.4.4-2 can solve that.
